# Generated by Django 4.2.29 on 2026-03-06 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driving', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CicloCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ciclo', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Ciclo de Carga',
                'verbose_name_plural': 'Ciclos de Carga',
                'ordering': ['ensayo', 'numero_ciclo'],
            },
        ),
        migrations.CreateModel(
            name='PuntoCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(choices=[('CARGA', 'Carga'), ('MANT', 'Mantenimiento'), ('DESC', 'Descarga')], max_length=5)),
                ('carga_kgf', models.FloatField()),
                ('desplazamiento_mm', models.FloatField()),
                ('tiempo_min', models.FloatField()),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos', to='load_tests.ciclocarga')),
            ],
            options={
                'verbose_name': 'Punto de Carga',
                'verbose_name_plural': 'Puntos de Carga',
                'ordering': ['ciclo', 'tiempo_min'],
            },
        ),
        migrations.CreateModel(
            name='EnsayoCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ensayo', models.DateField()),
                ('operador', models.CharField(blank=True, max_length=100)),
                ('norma', models.CharField(default='ASTM D3966', max_length=100)),
                ('cumple_criterio', models.BooleanField(blank=True, null=True)),
                ('hincado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ensayos', to='driving.hincado')),
            ],
            options={
                'verbose_name': 'Ensayo de Carga',
                'verbose_name_plural': 'Ensayos de Carga',
                'ordering': ['hincado', 'fecha_ensayo'],
            },
        ),
        migrations.AddField(
            model_name='ciclocarga',
            name='ensayo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclos', to='load_tests.ensayocarga'),
        ),
        migrations.AlterUniqueTogether(
            name='ciclocarga',
            unique_together={('ensayo', 'numero_ciclo')},
        ),
    ]
