# Generated by Django 5.2.12 on 2026-03-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='analysis_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
