# Generated by Django 4.2.29 on 2026-03-06 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hincado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punto_id', models.CharField(help_text='Ej: PV-01, PV-02', max_length=20)),
                ('fecha', models.DateField()),
                ('profundidad_total_m', models.FloatField(help_text='Profundidad total de hincado en metros')),
                ('observaciones', models.TextField(blank=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hincados', to='projects.proyecto')),
            ],
            options={
                'verbose_name': 'Hincado',
                'verbose_name_plural': 'Hincados',
                'ordering': ['proyecto', 'punto_id'],
                'unique_together': {('proyecto', 'punto_id')},
            },
        ),
        migrations.CreateModel(
            name='TramoHincado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tramo', models.PositiveIntegerField()),
                ('prof_inicio_m', models.FloatField()),
                ('prof_fin_m', models.FloatField()),
                ('tiempo_avance_min', models.FloatField()),
                ('clasificacion', models.CharField(blank=True, choices=[('Suave', 'Suave (< 1 min/tramo)'), ('Medio', 'Medio (1-3 min/tramo)'), ('Duro', 'Duro (3-5 min/tramo)'), ('Rechazo', 'Rechazo (> 5 min/tramo)')], max_length=10)),
                ('hincado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramos', to='driving.hincado')),
            ],
            options={
                'verbose_name': 'Tramo de Hincado',
                'verbose_name_plural': 'Tramos de Hincado',
                'ordering': ['hincado', 'numero_tramo'],
            },
        ),
    ]
